security:
    encoders:
        MemoQuest\Entity\User: plaintext

    providers:
        main:
            entity: { class: MemoQuest\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider:  main
            
        default:
            anonymous: ~
