user:
    type: rest
    resource: MemoQuest\Bundle\Controller\UserController

liste:
    type: rest
    parent: user
    resource: MemoQuest\Bundle\Controller\ListeController

mot:
    type: rest
    parent: liste
    resource: MemoQuest\Bundle\Controller\MotListeController
