user:
    type: rest
    resource: MemoQuest\Bundle\Controller\UserController

liste:
    type: rest
    parent: user
    resource: MemoQuest\Bundle\Controller\ListeController

contact:
    path:  /users/{userId}/listes/{listeId}/mots
    defaults: { _controller: MemoQuestBundle:MotListe:cget }
    requirements:
        _method:  GET
        userId: \d+
        listeId: \d+
