default:
path: /{name}
    defaults: { _controller: MemoQuestBundle:Default:index }

user:
    type: rest
    resource: MemoQuest\Bundle\Controller\UserController

quiz:
    type: rest
    resource: MemoQuest\Bundle\Controller\QuizController

quizz_content:
    type: rest
    parent: quiz
    resource: MemoQuest\Bundle\Controller\QuizContentController
    
get_user_liste_mots:
    path: /users/{userId}/listes/{listeId}/mots
    defaults: { _controller: MemoQuestBundle:MotListe:cget }
    requirements:
        _method:  GET
        userId: \d+
        listeId: \d+

get_user_liste_mot:
    path:  /users/{userId}/listes/{listeId}/mots/{id}
    defaults: { _controller: MemoQuestBundle:MotListe:get }
    requirements:
        _method:  GET
        userId: \d+
        listeId: \d+
        id: \d+

post_user_liste_mots:
    path:  /users/{userId}/listes/{listeId}/mots
    defaults: { _controller: MemoQuestBundle:MotListe:cpost }
    requirements:
        _method:  POST
        userId: \d+
        listeId: \d+

put_user_liste_mot:
    path:  /users/{userId}/listes/{listeId}/mots/{id}
    defaults: { _controller: MemoQuestBundle:MotListe:put }
    requirements:
        _method:  PUT
        userId: \d+
        listeId: \d+
        id: \d+

delete_user_liste_mot:
    path:  /users/{userId}/listes/{listeId}/mots/{id}
    defaults: { _controller: MemoQuestBundle:MotListe:delete }
    requirements:
        _method:  DELETE
        userId: \d+
        listeId: \d+
        id: \d+
        
get_user_liste_evaluations:
    path:  /users/{userId}/listes/{listeId}/evaluations
    defaults: { _controller: MemoQuestBundle:Evaluation:cget }
    requirements:
        _method:  GET
        userId: \d+
        listeId: \d+

get_user_liste_evaluation:
    path:  /users/{userId}/listes/{listeId}/evaluations/{id}
    defaults: { _controller: MemoQuestBundle:Evaluation:get }
    requirements:
        _method:  GET
        userId: \d+
        listeId: \d+
        id: \d+

post_user_liste_evaluations:
    path:  /users/{userId}/listes/{listeId}/evaluations
    defaults: { _controller: MemoQuestBundle:Evaluation:cpost }
    requirements:
        _method:  POST
        userId: \d+
        listeId: \d+

put_user_liste_evaluation:
    path:  /users/{userId}/listes/{listeId}/evaluations/{id}
    defaults: { _controller: MemoQuestBundle:Evaluation:put }
    requirements:
        _method:  PUT
        userId: \d+
        listeId: \d+
        id: \d+

delete_user_liste_evaluation:
    path:  /users/{userId}/listes/{listeId}/evaluations/{id}
    defaults: { _controller: MemoQuestBundle:Evaluation:delete }
    requirements:
        _method:  DELETE
        userId: \d+
        listeId: \d+
        id: \d+
