user:
    type: rest
    resource: MemoQuest\Bundle\Controller\UserController

liste:
    type: rest
    parent: user
    resource: MemoQuest\Bundle\Controller\ListeController

get_user_email:
    path: /users/{userEmail}
    defaults: { _controller: MemoQuestBundle:User:getByEmail }
    requirements:
        _method: GET
    
get_user_liste_mots:
    path: /users/{userId}/listes/{listeId}/mots
    defaults: { _controller: MemoQuestBundle:MotListe:cget }
    requirements:
        _method:  GET
        userId: \d+
        listeId: \d+

get_user_liste_mot:
    path:  /users/{userId}/listes/{listeId}/mots/{id}
    defaults: { _controller: MemoQuestBundle:MotListe:get }
    requirements:
        _method:  GET
        userId: \d+
        listeId: \d+
        id: \d+

post_user_liste_mots:
    path:  /users/{userId}/listes/{listeId}/mots
    defaults: { _controller: MemoQuestBundle:MotListe:cpost }
    requirements:
        _method:  POST
        userId: \d+
        listeId: \d+

put_user_liste_mot:
    path:  /users/{userId}/listes/{listeId}/mots/{id}
    defaults: { _controller: MemoQuestBundle:MotListe:put }
    requirements:
        _method:  PUT
        userId: \d+
        listeId: \d+
        id: \d+

delete_user_liste_mot:
    path:  /users/{userId}/listes/{listeId}/mots/{id}
    defaults: { _controller: MemoQuestBundle:MotListe:delete }
    requirements:
        _method:  DELETE
        userId: \d+
        listeId: \d+
        id: \d+
        
get_user_liste_evaluations:
    path:  /users/{userId}/listes/{listeId}/evaluations
    defaults: { _controller: MemoQuestBundle:Evaluation:cget }
    requirements:
        _method:  GET
        userId: \d+
        listeId: \d+

get_user_liste_evaluation:
    path:  /users/{userId}/listes/{listeId}/evaluations/{id}
    defaults: { _controller: MemoQuestBundle:Evaluation:get }
    requirements:
        _method:  GET
        userId: \d+
        listeId: \d+
        id: \d+

post_user_liste_evaluations:
    path:  /users/{userId}/listes/{listeId}/evaluations
    defaults: { _controller: MemoQuestBundle:Evaluation:cpost }
    requirements:
        _method:  POST
        userId: \d+
        listeId: \d+

put_user_liste_evaluation:
    path:  /users/{userId}/listes/{listeId}/evaluations/{id}
    defaults: { _controller: MemoQuestBundle:Evaluation:put }
    requirements:
        _method:  PUT
        userId: \d+
        listeId: \d+
        id: \d+

delete_user_liste_evaluation:
    path:  /users/{userId}/listes/{listeId}/evaluations/{id}
    defaults: { _controller: MemoQuestBundle:Evaluation:delete }
    requirements:
        _method:  DELETE
        userId: \d+
        listeId: \d+
        id: \d+
