<?php

namespace MemoQuest\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotDictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotDictRepository extends EntityRepository
{
}
