<?php

namespace MemoQuest\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotListeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotListeRepository extends EntityRepository
{
}
