<?php

namespace MemoQuest\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizContentRepository extends EntityRepository
{
}
